import { ArrowUpRight, ChevronRight, Search, SlidersHorizontal } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

const capabilities = [
  { name: '视觉理解', category: '多模态', description: '从图片中识别对象、结构和关系，输出稳定的 JSON 结果。', latency: '2.4s', price: '0.08', image: 'https://picsum.photos/seed/vision-market/1000/800', tone: 'from-[#d6f77b] to-[#718c2e]' },
  { name: '长文本摘要', category: '语言处理', description: '将长文档提炼成清晰、可执行的结论与行动项。', latency: '1.8s', price: '0.03', image: 'https://picsum.photos/seed/long-form/1000/800', tone: 'from-[#eee8db] to-[#888e82]' },
  { name: '知识检索', category: '知识增强', description: '在团队知识中找到带来源的答案，适合内部问答和助手。', latency: '0.9s', price: '0.02', image: 'https://picsum.photos/seed/retrieval/1000/800', tone: 'from-[#b4d2ff] to-[#526a86]' },
  { name: '语音转写', category: '音频处理', description: '把会议录音转成带时间戳的文本和摘要。', latency: '0.6s', price: '0.01', image: 'https://picsum.photos/seed/transcript/1000/800', tone: 'from-[#f7b18a] to-[#744d3d]' },
]

export function CapabilitiesPage() {
  const navigate = useNavigate(); const [active, setActive] = useState('全部'); const [query, setQuery] = useState('')
  const categories = ['全部', '多模态', '语言处理', '知识增强', '音频处理']
  const filtered = capabilities.filter((item) => (active === '全部' || item.category === active) && item.name.includes(query))
  return <section className="mx-auto max-w-[1500px] px-5 pb-32 pt-12 md:px-10 md:pt-20"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-5 text-sm text-[#c9f05b]">可组合的能力目录</p><h1 className="max-w-5xl text-5xl font-medium leading-[.95] tracking-[-.07em] text-[#f4f4ef] md:text-7xl">找到一块<br /><span className="text-white/35">能立即使用的积木。</span></h1></div><button onClick={() => navigate('/chat')} className="group flex items-center gap-3 self-start rounded-full bg-[#c9f05b] px-5 py-3 text-sm font-semibold text-[#11130f] md:self-end">打开调试台 <ArrowUpRight size={16} className="transition group-hover:translate-x-1 group-hover:-translate-y-1" /></button></div><div className="mt-20 flex flex-col gap-4 border-y border-white/10 py-5 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{categories.map((category) => <button key={category} onClick={() => setActive(category)} className={`rounded-full px-4 py-2 text-xs transition ${active === category ? 'bg-white text-[#11130f]' : 'border border-white/10 text-white/45 hover:border-[#c9f05b] hover:text-[#c9f05b]'}`}>{category}</button>)}</div><label className="flex items-center gap-3 text-sm text-white/40"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索能力" className="w-full bg-transparent outline-none placeholder:text-white/25 md:w-32" /></label></div><div className="mt-10 grid gap-4 md:grid-cols-2">{filtered.map((item) => <button key={item.name} onClick={() => navigate('/chat')} className={`group relative min-h-[420px] overflow-hidden rounded-[1.75rem] bg-gradient-to-br ${item.tone} p-7 text-left`}><img src={item.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-25 grayscale transition duration-700 group-hover:scale-105 group-hover:opacity-40" /><div className="absolute inset-0 bg-gradient-to-t from-[#11130f]/90 via-[#11130f]/10 to-transparent" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between text-xs uppercase tracking-[.18em] text-white/70"><span>{item.category}</span><SlidersHorizontal size={15} /></div><div><div className="mb-4 flex items-end justify-between gap-3"><h2 className="text-3xl font-medium tracking-[-.05em] text-white md:text-4xl">{item.name}</h2><ChevronRight size={22} className="transition group-hover:translate-x-2" /></div><p className="max-w-md text-sm leading-6 text-white/65">{item.description}</p><div className="mt-7 flex gap-8 text-xs text-white/50"><span>延迟 <strong className="ml-1 text-white">{item.latency}</strong></span><span>每次 <strong className="ml-1 text-white">¥{item.price}</strong></span></div></div></div></button>)}</div><p className="mt-8 text-xs text-white/30">当前展示平台骨架示例能力；正式数据接入 `capability-service` 的市场接口。</p></section>
}
